import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Footer, Navbar } from "../components/"
import { About, Cards, Contact, Events, Main } from "../sections/"
import { Element } from 'react-scroll'
import { motion } from 'framer-motion';



export default function Home() {
  return (
    <>
      <Head>
        <title>Hack Club ASIET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
      <motion.div initial="hidden" animate="visible" variants={{
        hidden: {
          scale: .8,
          opacity: 0
        },
        visible: {
          scale: 1,
          opacity: 1,
          transition: {
            delay: .4
          }
        },
      }}>
          <h1 className='title'>
            Hack Club ASIET
          </h1>
        </motion.div>
      </main>
      
      <Element name="Home">
        <Navbar />
        <Main />
      </Element>

      <Element name="About">
        <About />
      </Element>

      <Element name="Cards">
        <Cards />
      </Element>

      <Element name="Events">
        <Events />
      </Element>

      <Element name="Contact">
        <Contact />
      </Element>

      <Footer />


    </>
  )
}
